# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

workflows:
  version: 2
  commit:
    jobs:
      - runUnittestsExceptSQLConnectionTests
      - runUnittestsPostgres

commonYAMLStructure:
  - &restore_venv_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
  - &install_odbc
    run:
      command: sudo apt install unixodbc-dev
  - &install_venv_dependencies
    run:
      command: |
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
  - &save_venv_cache
    save_cache:
      paths:
        - ./venv
      key: v1-dependencies-{{ checksum "requirements.txt" }}

  - &activate-venv
    run:
      command: |
        . venv/bin/activate

jobs:
  runUnittestsExceptSQLConnectionTests:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - *install_odbc
      - *restore_venv_cache
      - *install_venv_dependencies
      - *save_venv_cache
      - *activate-venv
      - run:
          name: run utils tests
          command: |
            python -m tests.test_parser suite tests.utils

      - run:
          name: run cli tests
          command: |
            python -m tests.test_parser suite tests.cli


      - store_artifacts:
          path: test-reports
          destination: test-reports

  runUnittestsPostgres:
    docker:
      - image: circleci/python:3.6.1
        environment:
          SERVER: localhost
          DATABASE: circle_test
          USER: test
          PASS: test_pw
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_DB: circleci_test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test_pw

    working_directory: ~/repo

    steps:
      - checkout
      - *install_odbc
      - *restore_venv_cache
      - *install_venv_dependencies
      - *save_venv_cache
      - *activate-venv
      - run:
          name: run sql connector postgres
          command: |
            python -m tests.test_parser case tests.sql_functions.test_sql_connector.TestSQLConnector.test_postgres_connection


      - store_artifacts:
          path: test-reports
          destination: test-reports